# Generated by Django 5.2 on 2025-05-02 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_order_complete_alter_product_digital_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment_success',
            old_name='payment_time',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='payment_success',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='payment_success',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='payment_success',
            name='note',
        ),
        migrations.RemoveField(
            model_name='payment_success',
            name='order',
        ),
        migrations.RemoveField(
            model_name='payment_success',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='payment_success',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
