# Generated by Django 5.2 on 2025-05-03 11:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_payment_time_payment_success_timestamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_desc', models.TextField()),
                ('transaction_no', models.CharField(max_length=255)),
                ('response_code', models.CharField(max_length=10)),
                ('payment_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('bank_code', models.CharField(max_length=10)),
                ('card_type', models.CharField(max_length=20)),
                ('success', models.BooleanField(default=False)),
            ],
        ),
    ]
