# Generated by Django 5.2 on 2025-05-04 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_paymentrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='customer',
        ),
    ]
